import type { Metadata } from 'next';
import '@/config/globals.css';
import { Header } from '@/layouts/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <section>{children}</section>
      </body>
    </html>
  );
}
